### PR TITLE
Handle errors in client responses

### PR DESCRIPTION
**Pull request by pecigonzalo**
Handles errors in responses as described in https://github.com/segmentio/topicctl/issues/101. I've created 2 utility handling functions to avoid repeating so much code.
I could not think if a good function name.

image

Related: https://github.com/segmentio/topicctl/issues/101

### CODE REVIEW

**Comment by hhahn-tw** [comment]
Thanks for your PR!

> I could not think if a good function name.

I feel this. How about something like KafkaErrorsToErr? Longer, but it gives a hint at what it's doing.

Perhaps related: it would be nice if a single function could handle the two types of errors you're handling, to unify an interface to that conversion. Since they are of different types, though, this might end up ugly. Thoughts?

**Comment by pecigonzalo** [comment]
> I feel this. How about something like KafkaErrorsToErr? Longer, but it gives a hint at what it's doing.

Sounds better, as while `map[string]errors` is not Kafka specific, the implementation is.

> Perhaps related: it would be nice if a single function could handle the two types of errors you're handling, to unify an interface to that conversion. Since they are of different types, though, this might end up ugly. Thoughts?

That was my initial approach, but I could not generalize them without having the caller functions do some work as they have different types.
- `resp.Errors` being a `map[string]error` 
- `resp.Error` being just an `error`
- `resp.Resources` being a `[]kafka.IncrementalAlterConfigsResponseResource`

I think ideally `kafka-go` should not use these different types and instead bubble up to `resp.Errors` or `resp.Error`.

Im also not too familiar with Go Generics yet, as I have been programming in other langs lately, maybe there is a clean way to handle it with them.

**Comment by hhahn-tw** [comment]
Thanks for sharing your thoughts on what a single function design would look like - I don't have any concrete suggestions or ideas on what that could like and think your current implementation will be fine.

**Review by hhahn-tw — APPROVED** [review]
Thank you for the contributuion!

**Pull request merged**
